/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JOptionPane;

/**
 *
 * @author anewt
 */
public class Car extends javax.swing.JFrame {

    /**
     * Creates new form Car
     */
    public Car() {
        initComponents();
        cbxMake.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlMainPanel = new javax.swing.JPanel();
        lblLast = new javax.swing.JLabel();
        lblFirst = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        chkBike = new javax.swing.JCheckBox();
        chkCar = new javax.swing.JCheckBox();
        chkTruck = new javax.swing.JCheckBox();
        cbxMake = new javax.swing.JComboBox<>();
        radRed = new javax.swing.JRadioButton();
        radBlue = new javax.swing.JRadioButton();
        radBlack = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaArea1 = new javax.swing.JTextArea();
        btnList = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(null);

        pnlMainPanel.setBackground(new java.awt.Color(204, 204, 255));

        lblLast.setText("Last Name:");

        lblFirst.setText("First Name:");

        chkBike.setText("Bike");

        chkCar.setText("Car");
        chkCar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkCarItemStateChanged(evt);
            }
        });

        chkTruck.setText("Truck");

        cbxMake.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "< Pick Make >", "Chevy", "Ford", "Nissan", "Toyota" }));
        cbxMake.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxMakeItemStateChanged(evt);
            }
        });

        buttonGroup1.add(radRed);
        radRed.setText("Red");

        buttonGroup1.add(radBlue);
        radBlue.setText("Blue");

        buttonGroup1.add(radBlack);
        radBlack.setText("Black");
        radBlack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBlackActionPerformed(evt);
            }
        });

        txaArea1.setColumns(20);
        txaArea1.setRows(5);
        jScrollPane1.setViewportView(txaArea1);

        btnList.setText("List");
        btnList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListMouseClicked(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlMainPanelLayout = new javax.swing.GroupLayout(pnlMainPanel);
        pnlMainPanel.setLayout(pnlMainPanelLayout);
        pnlMainPanelLayout.setHorizontalGroup(
            pnlMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainPanelLayout.createSequentialGroup()
                .addGroup(pnlMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(pnlMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMainPanelLayout.createSequentialGroup()
                                .addGroup(pnlMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLast)
                                    .addComponent(lblFirst))
                                .addGap(43, 43, 43)
                                .addGroup(pnlMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(txtLastName)))
                            .addGroup(pnlMainPanelLayout.createSequentialGroup()
                                .addGroup(pnlMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnlMainPanelLayout.createSequentialGroup()
                                        .addComponent(chkBike)
                                        .addGap(40, 40, 40)
                                        .addComponent(chkCar))
                                    .addGroup(pnlMainPanelLayout.createSequentialGroup()
                                        .addComponent(radRed)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(radBlue)))
                                .addGap(36, 36, 36)
                                .addGroup(pnlMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radBlack)
                                    .addGroup(pnlMainPanelLayout.createSequentialGroup()
                                        .addComponent(chkTruck)
                                        .addGap(38, 38, 38)
                                        .addComponent(cbxMake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlMainPanelLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(btnList)
                        .addGap(107, 107, 107)
                        .addComponent(btnExit)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        pnlMainPanelLayout.setVerticalGroup(
            pnlMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnlMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLast)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(pnlMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirst)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(pnlMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkBike)
                    .addComponent(chkCar)
                    .addComponent(chkTruck)
                    .addComponent(cbxMake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(pnlMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radRed)
                    .addComponent(radBlue)
                    .addComponent(radBlack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnList)
                    .addComponent(btnExit))
                .addGap(17, 17, 17))
        );

        getContentPane().add(pnlMainPanel);
        pnlMainPanel.setBounds(10, 10, 580, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radBlackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBlackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radBlackActionPerformed

    
    
    
    
    
    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnExitMouseClicked

    private void cbxMakeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxMakeItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbxMakeItemStateChanged

    private void chkCarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkCarItemStateChanged
        // TODO add your handling code here:
        if (chkCar.isSelected()) {
            cbxMake.setVisible(true);
        } else {
            cbxMake.setVisible(false);
        }
    }//GEN-LAST:event_chkCarItemStateChanged

    private void btnListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListMouseClicked
        // TODO add your handling code here:
        String msg = "Last:  " + txtLastName.getText() + "\n";
        msg += "First:  " + txtFirstName.getText() + "\n";
        
        if (chkBike.isSelected()) {
            msg += "Vehicle:  Bike \n";
        }
        
        if (chkCar.isSelected() ) {
            msg += "Vehicle:  Car \n";
            switch(cbxMake.getSelectedIndex() ) {
                case 1:
                    msg += "Make: Chevy \n";
                    break;
                
                case 2:
                    msg += "Make: Ford \n";
                    break;
                
                case 3:
                    msg += "Make: Nissan \n";
                    break;   
                    
                case 4:
                    msg += "Make: Toyota \n";
                    break;    
            } // End Car
            
        if (chkTruck.isSelected()) {
            msg +=  "Vehicle: Truck \n";
        }    
        
        
        if (radRed.isSelected()) {
            msg += "Color: Red \n";
        }
        
        if (radBlue.isSelected()) {
            msg += "Color: Blue \n";
        }
        
        if (radBlack.isSelected()) {
            msg += "Color: Black \n";
        }
        
        msg+= "Comments: \n" + txaArea1.getText();
        
        JOptionPane.showMessageDialog(null, msg);
        
            
            
            
        }
    }//GEN-LAST:event_btnListMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Car.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Car.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Car.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Car.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Car().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnExit;
    public javax.swing.JButton btnList;
    public javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JComboBox<String> cbxMake;
    public javax.swing.JCheckBox chkBike;
    public javax.swing.JCheckBox chkCar;
    public javax.swing.JCheckBox chkTruck;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblFirst;
    public javax.swing.JLabel lblLast;
    public javax.swing.JPanel pnlMainPanel;
    public javax.swing.JRadioButton radBlack;
    public javax.swing.JRadioButton radBlue;
    public javax.swing.JRadioButton radRed;
    public javax.swing.JTextArea txaArea1;
    public javax.swing.JTextField txtFirstName;
    public javax.swing.JTextField txtLastName;
    // End of variables declaration//GEN-END:variables
}
